"""PR-CONTEXT reproducibility and restart bundle -- build, then verify by extraction.

Includes everything required to reproduce or restart the analysis, and deliberately excludes
the bulk sequence and metadata caches, which are exactly reconstructable from manifests that
ARE included:

  * 6,621 plasmid sequences  -> plasmid_retrieval_receipts.tsv carries accession.version,
    the canonical efetch URL and raw_sha256 for every one.
  * 21,955 window blocks     -> shared_context_blocks.tsv carries replicon, block start/end,
    topology, wrap/truncate state and extracted_sequence_sha256 for every one.
  * NCBI metadata caches     -> re-fetchable; the parsed tables are included.

The archive is verified by extracting every member and re-hashing it against the file it came
from, not by trusting the writer.
"""
import argparse, csv, hashlib, json, os, subprocess, sys, tarfile, datetime

VERSION = "pr_context_build_bundle_v1.0.0"

EXCLUDE_CLASSES = {"sequence_cache_plasmid", "sequence_cache_window", "metadata_cache",
                   "tool_work_scratch", "tool_database", "tool_output_raw", "bundle"}


def sha256_file(p):
    h = hashlib.sha256()
    with open(p, "rb") as fh:
        for c in iter(lambda: fh.read(1 << 20), b""):
            h.update(c)
    return h.hexdigest()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", required=True)
    ap.add_argument("--scripts", required=True)
    ap.add_argument("--manifest", required=True)
    ap.add_argument("--bundle", required=True)
    a = ap.parse_args()

    rows = list(csv.DictReader(open(a.manifest, encoding="utf-8"), delimiter="\t"))
    members = []
    excluded = []
    for r in rows:
        rel = r["relative_path"]
        if r["artefact_class"] in EXCLUDE_CLASSES:
            excluded.append(r)
            continue
        src = (os.path.join(a.scripts, rel[len("scripts/"):]) if rel.startswith("scripts/")
               else os.path.join(a.root, rel))
        if os.path.exists(src):
            members.append((rel, src))
    # closure manifests themselves
    for extra in ("closure/manifest_local.tsv", "closure/manifest_server.tsv"):
        p = os.path.join(a.root, extra)
        if os.path.exists(p) and not any(m[0] == extra for m in members):
            members.append((extra, p))
    members.sort()
    print("%s\n  members to archive: %d | excluded by class: %d"
          % (VERSION, len(members), len(excluded)))

    pre = {rel: (os.path.getsize(src), sha256_file(src)) for rel, src in members}
    if os.path.exists(a.bundle):
        os.remove(a.bundle)
    with tarfile.open(a.bundle, "w:gz") as t:
        for rel, src in members:
            t.add(src, arcname="pr_context/" + rel)
    bs, bh = os.path.getsize(a.bundle), sha256_file(a.bundle)

    # verify: tar test + re-hash every extracted member
    tt = subprocess.run(["tar", "tzf", a.bundle], capture_output=True, text=True)
    bad, n = [], 0
    with tarfile.open(a.bundle, "r:gz") as t:
        names = set(t.getnames())
        for rel, (sz, sh) in pre.items():
            m = "pr_context/" + rel
            if m not in names:
                bad.append(rel + " (absent from archive)")
                continue
            data = t.extractfile(m).read()
            n += 1
            if len(data) != sz or hashlib.sha256(data).hexdigest() != sh:
                bad.append(rel + " (size or hash differs)")

    # bundle-internal manifest
    man = os.path.join(a.root, "closure", "BUNDLE_SHA256SUMS.txt")
    with open(man, "w", encoding="utf-8", newline="\n") as fh:
        for rel, (sz, sh) in sorted(pre.items()):
            fh.write("%s  %s\n" % (sh, rel))
    exm = os.path.join(a.root, "closure", "BUNDLE_EXCLUSIONS.tsv")
    with open(exm, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("relative_path\tbytes\tsha256\tartefact_class\treconstructable_from\n")
        REC = {"sequence_cache_plasmid": "plasmid_retrieval_receipts.tsv "
                                         "(accession.version + canonical URL + raw_sha256)",
               "sequence_cache_window": "shared_context_blocks.tsv "
                                        "(replicon + coordinates + extracted_sequence_sha256)",
               "metadata_cache": "NCBI Datasets / E-utilities, re-fetchable; parsed tables "
                                 "are inside the bundle",
               "tool_output_raw": "MOB-suite 3.1.9 rerun; aggregated table is in the bundle",
               "tool_work_scratch": "regenerated by the pipeline",
               "tool_database": "mob_init / conda install"}
        for r in excluded:
            fh.write("\t".join([r["relative_path"], r["bytes"], r["sha256"],
                                r["artefact_class"],
                                REC.get(r["artefact_class"], "")]) + "\n")

    res = {"builder": VERSION,
           "built_utc": datetime.datetime.now(datetime.timezone.utc)
           .strftime("%Y-%m-%dT%H:%M:%SZ"),
           "bundle_path": a.bundle, "bundle_bytes": bs, "bundle_sha256": bh,
           "members": len(members), "members_reverified_from_archive": n,
           "member_mismatches": len(bad), "tar_test_exit": tt.returncode,
           "excluded_files": len(excluded),
           "excluded_bytes": sum(int(r["bytes"]) for r in excluded),
           "exclusion_policy": sorted(EXCLUDE_CLASSES),
           "sha256sums_file": man, "exclusions_file": exm}
    json.dump(res, open(os.path.join(a.root, "closure", "BUNDLE_RECEIPT.json"), "w",
                        encoding="utf-8", newline="\n"), indent=2)
    print("  bundle: %s" % a.bundle)
    print("  bytes %d | sha256 %s" % (bs, bh))
    print("  tar test exit %d | members re-hashed from the archive %d | mismatches %d"
          % (tt.returncode, n, len(bad)))
    for b in bad[:10]:
        print("    ", b)
    print("  excluded %d files (%.3f GB) - all exactly reconstructable, listed in %s"
          % (len(excluded), sum(int(r["bytes"]) for r in excluded) / 1e9,
             os.path.basename(exm)))
    sys.exit(0 if not bad and tt.returncode == 0 else 4)


if __name__ == "__main__":
    main()
